In [10]:
import numpy as np
import pandas as pd
data=pd.read_csv("E:\cleaned_all_phones.csv")
datac=data
datac
datac.head()

,phone_name,brand,os,inches,resolution,battery,battery_type,ram(GB),announcement_date,weight(g),...,video_1080p,video_4K,video_8K,video_30fps,video_60fps,video_120fps,video_240fps,video_480fps,video_960fps,price(USD)
0,Y6II Compact,Huawei,Android 5.1,5.0,720x1280,2200,Li-Po,2,2016-09-01,140.0,...,False,False,False,True,False,False,False,False,False,120.0
1,K20 plus,LG,Android 7.0,5.3,720x1280,2700,Li-Ion,2,2016-12-01,140.0,...,True,False,False,True,False,False,False,False,False,100.0
2,P8 Lite (2017),Huawei,Android 7.0,5.2,1080x1920,3000,Li-Ion,4,2017-01-01,147.0,...,True,False,False,True,False,False,False,False,False,420.0
3,Redmi Note 4,Xiaomi,Android 6.0,5.5,1080x1920,4100,Li-Po,4,2017-01-01,165.0,...,True,False,False,True,False,True,False,False,False,150.0
4,P10,Huawei,Android 7.0,5.1,1080x1920,3200,Li-Ion,4,2017-02-01,145.0,...,True,True,False,True,True,False,False,False,False,420.0

In [12]:
datac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   phone_name         1512 non-null   object
 1   brand              1512 non-null   object
 2   os                 1512 non-null   object
 3   inches             1512 non-null   float64
 4   resolution         1512 non-null   object
 5   battery            1512 non-null   int64
 6   battery_type       1512 non-null   object
 7   ram(GB)            1512 non-null   int64
 8   announcement_date  1512 non-null   object
 9   weight(g)          1512 non-null   float64
 10  storage(GB)        1512 non-null   int64
 11  video_720p         1512 non-null   bool
 12  video_1080p        1512 non-null   bool
 13  video_4K           1512 non-null   bool
 14  video_8K           1512 non-null   bool
 15  video_30fps        1512 non-null   bool
 16  video_60fps        1512 non-null   bool
 17  video_120fps       1512 non-null   bool
 18  video_240fps       1512 non-null   bool
 19  video_480fps       1512 non-null   bool
 20  video_960fps       1512 non-null   bool
 21  price(USD)         1512 non-null   float64
dtypes: bool(10), float64(3), int64(3), object(6)
memory usage: 156.6+ KB

In [25]:
#How many unique  mobile brands are there in the data provided
len(datac["brand"].unique())

13

In [ ]:
#By using unique() metgod we get to know there are 13 types of brands are there in our dataset

In [27]:
#What is the average ram size of all the collected data
datac["ram(GB)"].mean()

6.6838624338624335

In [ ]:
#By using mean method we get the average of ram column i.e 6.6838624338624335

In [28]:
#Which phone is having the maximum and minimum battery capacity
datac["battery"].max()

7250

In [31]:
datac.loc[datac["battery"]==7250]

,phone_name,brand,os,inches,resolution,battery,battery_type,ram(GB),announcement_date,weight(g),...,video_1080p,video_4K,video_8K,video_30fps,video_60fps,video_120fps,video_240fps,video_480fps,video_960fps,price(USD)
573,V6,Honor,Android 10,10.4,1200x2000,7250,Li-Po,8,2020-05-19,480.0,...,True,False,False,True,False,False,False,False,False,280.0

In [33]:
datac["battery"].min()

1821

In [34]:
datac.loc[datac["battery"]==1821]

,phone_name,brand,os,inches,resolution,battery,battery_type,ram(GB),announcement_date,weight(g),...,video_1080p,video_4K,video_8K,video_30fps,video_60fps,video_120fps,video_240fps,video_480fps,video_960fps,price(USD)
62,iPhone 8,Apple,iOS 11,4.7,750x1334,1821,Li-Ion,2,2017-09-12,148.0,...,True,True,False,True,True,True,True,False,False,210.0
536,iPhone SE (2020),Apple,iOS 13,4.7,750x1334,1821,Li-Ion,3,2020-04-15,148.0,...,True,True,False,True,True,True,True,False,False,189.5

In [ ]:
#v6 of honor brand is having maximum battery i.e 7250 and iphone 8 and iphone SE(2020) are having least battery i.e 1821

In [36]:
#What is the maximum battery capacity provided by Huawei Company
g=datac.groupby("brand")
g.agg({'battery':[min,max],"ram(GB)":[min,max]})

        battery       ram(GB)
            min   max     min max
brand
Apple      1821  4352       2   6
Google     2700  5003       4  12
Honor      3000  7250       2  16
Huawei     2200  7000       1  12
LG         2410  5000       1   8
Lenovo     3000  7000       2  18
OnePlus    3300  5000       4  24
Oppo       2900  5000       2  16
Realme     3410  6000       2  24
Samsung    1950  7000       1  16
Sony       2300  5000       2  12
Vivo       4000  6000       2  16
Xiaomi     3000  6000       1  24

In [ ]:
#7000 is the maximum battery provided by Huawei company

In [41]:
#Which Phone brand is providing the highest and lowest ram
datac["ram(GB)"].max()
datac.loc[datac['ram(GB)']==24]

,phone_name,brand,os,inches,resolution,battery,battery_type,ram(GB),announcement_date,weight(g),...,video_1080p,video_4K,video_8K,video_30fps,video_60fps,video_120fps,video_240fps,video_480fps,video_960fps,price(USD)
1505,Redmi K60 Ultra,Xiaomi,Android 13,6.67,1220x2712,5000,Li-Po,24,2023-08-15,204.0,...,True,True,True,False,True,False,False,False,True,330.0
1506,Ace 2 Pro,OnePlus,Android 13,6.74,1240x2772,5000,Li-Po,24,2023-08-16,210.0,...,True,True,False,True,True,True,True,False,False,380.0
1510,GT5 240W,Realme,Android 13,6.74,1240x2772,4600,Li-Po,24,2023-08-28,205.0,...,True,True,False,False,True,False,False,False,False,470.0

In [44]:
datac["ram(GB)"].min()
datac.loc[datac['ram(GB)']==1]

,phone_name,brand,os,inches,resolution,battery,battery_type,ram(GB),announcement_date,weight(g),...,video_1080p,video_4K,video_8K,video_30fps,video_60fps,video_120fps,video_240fps,video_480fps,video_960fps,price(USD)
27,Y3 (2017),Huawei,Android 6.0,5.00,480x854,2200,Li-Ion,1,2017-05-01,175.0,...,False,False,False,True,False,False,False,False,False,230.00
28,Z4,Samsung,Tizen 3.0,4.50,480x800,2050,Li-Ion,1,2017-05-01,143.0,...,False,False,False,True,False,False,False,False,False,240.00
69,Galaxy J2 (2017),Samsung,Android 7.0,4.70,540x960,2000,Li-Ion,1,2017-10-01,130.0,...,False,False,False,True,False,False,False,False,False,500.00
133,Y3 (2018),Huawei,Android 8.0 Oreo,5.00,480x854,2280,Li-Ion,1,2018-05-01,175.0,...,False,False,False,True,False,False,False,False,False,1300.00
182,Galaxy J2 Core,Samsung,Android 8.1 Oreo,5.00,540x960,2600,Li-Ion,1,2018-08-01,154.0,...,True,False,False,True,False,False,False,False,False,200.00
230,Galaxy J4 Core,Samsung,Android 8.1 Oreo,6.00,720x1480,3300,Li-Ion,1,2018-11-01,177.0,...,True,False,False,True,False,False,False,False,False,120.00
236,Y5 lite (2018),Huawei,Android 8.1 Oreo,5.45,720x1440,3020,Li-Ion,1,2018-12-01,142.0,...,True,False,False,True,False,False,False,False,False,130.00
244,Redmi Go,Xiaomi,Android 8.1 Oreo,5.00,720x1280,3000,Li-Ion,1,2019-01-01,137.0,...,True,False,False,True,False,False,False,False,False,100.00
304,Galaxy A2 Core,Samsung,Android 8.0 Oreo,5.00,540x960,2600,Li-Ion,1,2019-04-01,142.0,...,True,False,False,True,False,False,False,False,False,290.00
363,K20 (2019),LG,Android 9.0 Pie,5.45,480x960,3000,Li-Ion,1,2019-08-01,152.0,...,True,False,False,True,False,False,False,False,False,160.00
550,Galaxy J2 Core (2020),Samsung,Android 8.1 Oreo,5.00,540x960,2600,Li-Ion,1,2020-04-27,154.0,...,True,False,False,True,False,False,False,False,False,238.19

In [ ]:
#Redmi k60 ultra,Ace 2 pro,Gt5 240 are having the maximum ram and y3(2017),z4,Galaxy z2(2017) etc are having the minimun ram

In [48]:
#How many phones has android 7.0 as there operating system
len(datac.loc[datac["os"]=="Android 7.0"])

33

In [ ]:
#33 phones are having os android 7.0

In [49]:
#Which phine is the oldest
datac["announcement_date"].min()

'2016-09-01'

In [56]:
datac.loc[datac['announcement_date']=='2016-09-01']

,phone_name,brand,os,inches,resolution,battery,battery_type,ram(GB),announcement_date,weight(g),...,video_1080p,video_4K,video_8K,video_30fps,video_60fps,video_120fps,video_240fps,video_480fps,video_960fps,price(USD)
0,Y6II Compact,Huawei,Android 5.1,5.0,720x1280,2200,Li-Po,2,2016-09-01,140.0,...,False,False,False,True,False,False,False,False,False,120.0

In [ ]:
#Y6II compact is the oldest phone

In [64]:
#hich brand produced maximum number of phone in the given data
a=datac.groupby("brand")
a["brand"].count()

brand
Apple       22
Google      19
Honor      124
Huawei     137
LG          75
Lenovo      43
OnePlus     47
Oppo       213
Realme     157
Samsung    206
Sony        37
Vivo       168
Xiaomi     264
Name: brand, dtype: int64

In [ ]:
#xiaomi has the highest no of phones

In [ ]:
#Give the count of phones supporting

In [65]:
#4k video
datac['video_4K'].value_counts()

True     801
False    711
Name: video_4K, dtype: int64

In [66]:
#8k video
datac['video_8K'].value_counts()

False    1426
True       86
Name: video_8K, dtype: int64

In [69]:
#2k video
datac['video_1080p'].value_counts()

True     1503
False       9
Name: video_1080p, dtype: int64

In [ ]:
# There are 801 phones having 4k video,86 phones having 8k videos,1503 phones have 2k video

In [70]:
#10. How many phones supports Li-Po and Li-ion Battery
a=datac.groupby("battery_type")
a["battery_type"].count()

battery_type
Li-Ion     270
Li-Po     1242
Name: battery_type, dtype: int64

In [ ]:
#270 phones support Li-Ion,1242 supports Li-Po

In [101]:
# How many sony phones supports 720x1280 resolution
b=(datac["resolution"]=="720x1280")&(datac["brand"]=='Sony')
datac[b]["phone_name"].count()

5

In [ ]:
# There are 5 phones from sony that supports 720x1280 resolution

In [109]:
#12. Print a pivot table for finding the average weights ,total weights,based on brand and battery type
a=pd.pivot_table(datac,index='brand',columns='battery_type',values="weight(g)",margins=True)
a

battery_type      Li-Ion       Li-Po         All
brand
Apple         186.227273         NaN  186.227273
Google        190.666667  176.923077  181.263158
Honor         165.333333  190.611570  190.000000
Huawei        158.354839  187.556604  180.948905
LG            154.851852  183.812500  173.386667
Lenovo        190.142857  218.586207  209.325581
OnePlus              NaN  191.553191  191.553191
Oppo          157.833333  183.174603  180.319249
Realme        166.833333  189.688742  188.815287
Samsung       178.531250  196.727273  188.247573
Sony          177.333333  178.769231  177.837838
Vivo                 NaN  190.232143  190.232143
Xiaomi        179.294118  195.906883  194.837121
All           173.040741  190.809179  187.636243

In [ ]:
#above shown is the pivot table showinh the average and all weights for combination of battery type and brand